#!/usr/bin/env ruby

$:<< 'lib'
require 'highline/import'
require 'langston'
require 'curses_printer'

width = ask("Width [33]: ") { |q| q.default = 33 }.to_i
height = ask("Height [33]: ") { |q| q.default = 33 }.to_i
gens = ask("Generations [100]: ") { |q| q.default = 100  }.to_i


puts "Running Langston's ant with width: #{width} height: #{height} gens: #{gens}"
puts
puts
Langston.new(width, height, CursesPrinter).run(gens)
