/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'matt' at '8/16/15 9:37 PM' with Gradle 2.6
 *
 * @author matt, @date 8/16/15 9:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
