/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'shah' at '8/13/15 8:13 PM' with Gradle 2.5
 *
 * @author shah, @date 8/13/15 8:13 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
