/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shah' at '8/13/15 8:29 PM' with Gradle 2.5
 *
 * @author shah, @date 8/13/15 8:29 PM
 */
public class Library {
    public boolean someLibraryMethod() { return true; }
}
