package com.xdd;

import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertEquals;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'shah' at '8/13/15 8:29 PM' with Gradle 2.5
 *
 * @author shah, @date 8/13/15 8:29 PM
 */
public class DayFinderTest {

    @Test public void itFindsTheDayNumberWithTheSmallestTemperatureSpread() throws IOException {
        DayProvider dayProvider = new DayProvider("data/weather.dat");
        DayFinder dayFinder = new DayFinder(dayProvider);

        Day day = dayFinder.getDayWithSmallestTemperatureSpread();

        assertEquals("14",day.getNumericDay());
    }
}
