/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'shah' at '8/13/15 8:13 PM' with Gradle 2.5
 *
 * @author shah, @date 8/13/15 8:13 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
