/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shah' at '8/21/15 8:02 AM' with Gradle 2.5
 *
 * @author shah, @date 8/21/15 8:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
